apiVersion: v1
kind: Namespace
metadata:
  name: sdn
  labels:
    app.kubernetes.io/name: sdn-project
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted