apiVersion: v1
kind: Service
metadata:
  name: sdn-frontend
  namespace: sdn
  labels:
    app.kubernetes.io/name: sdn-project
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: sdn-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP