module.exports = {
  User: require("./User"),
  Address: require("./Address"),
  Category: require("./Category"),
  Product: require("./Product"),
  Order: require("./Order"),
  OrderItem: require("./OrderItem"),
  Payment: require("./Payment"),
  ShippingInfo: require("./ShippingInfo"),
  ReturnRequest: require("./ReturnRequest"),
  Bid: require("./Bid"),
  Review: require("./Review"),
  Message: require("./Message"),
  Coupon: require("./Coupon"),
  Inventory: require("./Inventory"),
  Feedback: require("./Feedback"),
  SellerFeedback: require("./SellerFeedback"),
  Dispute: require("./Dispute"),
  Store: require("./Store"),
};
